site_name: ForgeGradle
#theme:

site_description: Documentation for ForgeGradle the gradle plugin for Minecraft
repo_url: https://github.com/MinecraftForge/ForgeGradle

nav:
  - Introduction: index.md
  - Cook Book: cookbook.md
  - User Guide: user-guide/shading.md
  - Shading: user-guide/shading.md
  - Minecraft{} Block: reference/mcblock.md
  - Adept Reference: reference/mcblock.md
  - Tasksreference/tasks.md
